name: jest

on: pull_request

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install modules
        run: npm install && npm install -g jest

      - name: Run jest
        run: jest --config=src/tests/jest.config.json  --testPathPattern=src/tests/unit/ --forceExit
